// Generated by Wrangler on Sun Jul 14 2024 21:28:55 GMT+0900 (日本標準時)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

namespace NodeJS {
  interface ProcessEnv {
    DB: D1Database;
  }
}

interface CloudflareEnv {
  DB: D1Database;
}
